#! /bin/sh

sxhkd -m -1 &
xrandr --dpi 140 &
~/dotfiles/scripts/launch-polybar.sh &
~/.fehbg &
~/dotfiles/scripts/update-theme.sh &
nm-applet &
if [ ! pgrep redshift ]; then
    redshift &
fi
compton &

bspc monitor -d I II III IV V VI VII VIII IX X XI XII

bspc config border_width         3
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a '*:telegram-desktop' desktop=XI
bspc rule -a '*:thunderbird' desktop=XII

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focus_follows_pointer true

bspc config normal_border_color "#01579B"
bspc config focused_border_color "#26A69A"
bspc config urgent_border_color "#F44336"
bspc config presel_feedback_color "#FF9800"

# Setup monitors
#i=1
#for monitor in $(bspc query -M); do
#    bspc monitor $monitor \
#        -n "$i" \
#        -d {One,Two,Three,Four,Five,Six,Seven,Eight,Nine,Ten}
#    let i++
#done
#unset i
#
#nitrogen --restore &
#
#bspc wm --adopt-orphans
